### PR TITLE
Installed and setup husky

### LINKED ISSUE #38: Husky
Install and setup husky for next.js app

On development branch.

### PR DESCRIPTION
**Pull request by sabhas**
### Issue
* closes #38 

### Implementation

* installed husky npm package as dev dependency
* added a prepare script in package.json which will initialize husky whenever `npm install` or `npm run build` commands will be executed
* added a pre-commit hook that will execute `npm run lint`

### CODE REVIEW

**Comment by 90barricade93** [comment]
Hello Sabir, 

Thank you for the effort! 
but the main is locked. 

I should have stated in the issue that the source should be development.

Development  >> husky magic >> main 

We deploy the main via vercel eventually.

Sorry for the inconvenience.
(I didn't expect collaborators this quick ;D)

Best regards,
Raymond

B.t.w. any interest to join the repo's discord?

https://discord.gg/NBaC49M5

**Comment by sabhas** [comment]
> Hello Sabir,
> 
> Thank you for the effort! but the main is locked.
> 
> I should have stated in the issue that the source should be development.
> 
> Development >> husky magic >> main
> 
> We deploy the main via vercel eventually.
> 
> Sorry for the inconvenience. (I didn't expect collaborators this quick ;D)
> 
> Best regards, Raymond
> 
> B.t.w. any interest to join the repo's discord?
> 
> https://discord.gg/NBaC49M5

Hey Raymond!

Thanks for the invitation to discord server.

I have read the contribution guide on discord. I just saw that you have added contributing guide in README but we should add separate CONTRIBUTING.md to repo too.

For the current PR, I updated the base to development. Is it enough or should I open a new PR and close this one?

**Comment by 90barricade93** [comment]
> Hey Raymond!
> 
> Thanks for the invitation to discord server.
> 
> I have read the contribution guide on discord. I just saw that you have added contributing guide in README but we should add separate CONTRIBUTING.md to repo too.
> 
> For the current PR, I updated the base to development. Is it enough or should I open a new PR and close this one?

Good suggestion, we add "CONTRIBUTING.md" to the issues!
Can i merge your commit to development branch now? 
Then a new PR won't be necessary.

**Comment by sabhas** [comment]
> > Hey Raymond!
> > 
> > Thanks for the invitation to discord server.
> > 
> > I have read the contribution guide on discord. I just saw that you have added contributing guide in README but we should add separate CONTRIBUTING.md to repo too.
> > 
> > For the current PR, I updated the base to development. Is it enough or should I open a new PR and close this one?
> 
> Good suggestion, we add "CONTRIBUTING.md" to the issues!
> Can i merge your commit to development branch now? 
> Then a new PR won't be necessary.

Yes, you can merge it. It's ready.

**Comment by 90barricade93** [comment]
Merged!, thank you for your patience, Sabir.

Op wo 31 jul. 2024 12:00 schreef Sabir Hassan ***@***.***>:

**Pull request merged**
